spring:
    datasource:
        url: jdbc:mariadb://192.168.99.100:3306/playerdetails
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: create